language: objective-c
osx_image: xcode7.1
xcode_project: UIViewRecursiveUtils.xcodeproj

cache:
  directories:
    - $HOME/.cocoapods

before_install:
  - gem install cocoapods xcpretty --no-ri --no-rdoc
  - set -o pipefail
  - xcodebuild clean -project UIViewRecursiveUtils.xcodeproj -scheme UIViewRecursiveUtils -sdk iphonesimulator | xcpretty -c

script:
  - pod lib lint
  - xcodebuild -project UIViewRecursiveUtils.xcodeproj -scheme UIViewRecursiveUtils -sdk iphonesimulator | xcpretty -c
